<hr>

<p><br>Trouble or questions?  Please email <i>copyright2023 AT pglaf.org,</i>
for clearance questions, or <i>pgww AT lists.pglaf.org</i> for
production or status questions.
</p>

<p>The ebookmaker software is available as a free download,
if you would rather run it on your own system.
You can find the software for download here: <a href="https://github.com/gutenbergtools/ebookmaker">https://github.com/gutenbergtools/ebookmaker</a></p>

 </body>
</html>
